package com.expensetracker.security;

import com.expensetracker.entity.User;
import lombok.Getter;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.stream.Collectors;

/**
 * Spring Security's {@link UserDetails} adapter for our {@link User} entity.
 *
 * <p>Decouples the security layer from the JPA entity so that the entity
 * can evolve independently without breaking the Spring Security contract.
 * The {@code id} and {@code email} extra fields are exposed for convenience
 * inside services that receive an {@link UserPrincipal} from
 * {@code @AuthenticationPrincipal}.
 */
@Getter
public class UserPrincipal implements UserDetails {

    private final Long   id;
    private final String username;
    private final String email;
    private final String password;
    private final boolean enabled;
    private final Collection<? extends GrantedAuthority> authorities;

    private UserPrincipal(Long id, String username, String email,
                          String password, boolean enabled,
                          Collection<? extends GrantedAuthority> authorities) {
        this.id          = id;
        this.username    = username;
        this.email       = email;
        this.password    = password;
        this.enabled     = enabled;
        this.authorities = authorities;
    }

    /**
     * Factory method — converts a JPA {@link User} into a
     * Spring Security {@link UserDetails} instance.
     */
    public static UserPrincipal build(User user) {
        var authorities = user.getRoles().stream()
            .map(role -> new SimpleGrantedAuthority(role.getName().name()))
            .collect(Collectors.toUnmodifiableSet());

        return new UserPrincipal(
            user.getId(),
            user.getUsername(),
            user.getEmail(),
            user.getPassword(),
            Boolean.TRUE.equals(user.getIsActive()),
            authorities
        );
    }

    // ── UserDetails contract ─────────────────────────────────────────
    // getAuthorities(), getPassword(), getUsername() → generated by @Getter
    // isEnabled()                                    → generated by @Getter on 'boolean enabled'

    @Override public boolean isAccountNonExpired()     { return true; }
    @Override public boolean isAccountNonLocked()      { return true; }
    @Override public boolean isCredentialsNonExpired() { return true; }
    // DO NOT add isEnabled() here — @Getter already generates it from 'boolean enabled'.
    // Duplicating it causes "method isEnabled() is already defined" compile error.
}
